# Copy and paste on config.py

USER = ''
PASSWORD = ''
CLIENT_KEY = '' # set your client key
CLIENT_SECRET = '' # set your secret key

BASE_URL = 'https://sired.sardegnaturismo.it/TurismoDroneService' # 'https://sired.sardegnaturismo.it/TurismoDroneServiceBA'
REQUEST_TOKEN_URL = 'GetRequestToken.aspx'
USER_AUTHORIZATION_URL = 'UserAuthorize.aspx'
ACCESS_TOCKEN_URL = 'GetAccessToken.aspx'

FIELDS_LIST = [
    'Anno',
    'CategoriaRegione',
    'CodiceComune',
    'CodiceISTATTipoStruttura',
    'CodiceIstatStelle',
    'CodiceRegione',
    'CodiceRegioneTipoStruttura',
    'Comune',
    'Denominazione',
    'Struttura',
    'IdStruttura',
    'IndirizzoStruttura',
    'IsAttivo_Tariffe',
    'IsAttivo_ISTAT',
    'NumeroStrutture',
    'Provincia',
    'Telefono',
    'TelefonoStruttura',
    'TipoStruttura',
    'TotaleAppartamenti',
    'TotaleBagni',
    'TotaleCamere_ISTAT',
    'TotaleCamere_Tariffe',
    'TotaleLetti',
    'IdStudio',
    'Id1',
    'Frazione',
    'CodiceStruttura',
    'IsDipendenza',
    'IsCasaMadre',
    'IdCasaMadre',
    'Fax',
    'E_Mail_Tariffe',
    'Web',
    'TipoAlbergo',
    'TipoApertura',
    'NoteStruttura',
    'IsOmessaDenuncia',
    'IsSecondaDenuncia',
    'IsRitardo',
    'Apertura1Da',
    'Apertura1A',
    'Apertura2Da',
    'Apertura2A',
    'Apertura3Da',
    'Apertura3A',
    'IndirizzoChiusura',
    'FrazioneChiusura',
    'ComuneChiusura',
    'CapChiusura',
    'ProvChiusura',
    'TelefonoChiusura',
    'FaxChiusura',
    'Gestore',
    'NomeGes',
    'IndirizzoGes',
    'ComuneGes',
    'ProvinciaGes',
    'TelefonoGes',
    'CodiceFiscaleGes',
    'DataNascitaGes',
    'ComuneNascitaGes',
    'FisicaGiuridicaGes',
    'GestioneGes',
    'RagioneSociale',
    'Proprietario',
    'IndirizzoPro',
    'ComunePro',
    'ProvinciaPro',
    'TelefonoPro',
    'Note',
    'CertifQA',
    'AttoNumero',
    'AttoDel',
    'DataCessazione',
    'CodiceFiscalePro',
    'AttoComune',
    'DenunciaApertura',
    'DataDenuncia',
    'DipendentiTotali',
    'DipendentiParziale',
    'DipendentiStagionale',
    'E_Mail_ISTAT',
    'IsGennaio',
    'IsFebbraio',
    'IsMarzo',
    'IsAprile',
    'IsMaggio',
    'IsGiugno',
    'IsLuglio',
    'IsAgosto',
    'IsSettembre',
    'IsOttobre',
    'IsNovembre',
    'IsDicembre',
    'IdRagioneSociale'
]